// <auto-generated />
using System;
using MahdiShop.DataLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MahdiShop.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230519175949_add see number to product")]
    partial class addseenumbertoproduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MahdiShop.DataLayer.Models.Product.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "All of the thing that can eat",
                            Name = "food"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "All of the thing that Use in home",
                            Name = "HomeTools"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "All of the thing that work with electronic",
                            Name = "Eletrition tools"
                        });
                });

            modelBuilder.Entity("MahdiShop.DataLayer.Models.Product.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Profile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "the best",
                            Name = "tv",
                            Price = 14000000m,
                            Profile = "/css/55f21061-6ed3-4890-9eea-0b666a711af9.jpg"
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "the best food in iran",
                            Name = "sandwich",
                            Price = 15000m,
                            Profile = "/css/d77a4624-8f71-47eb-b94b-bb517e2f3db7.jpg"
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "blue and black",
                            Name = "mobl",
                            Price = 5000000m,
                            Profile = "/css/7fd072b6-3bd1-453c-90e2-07e29fe3b12a.jpg"
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "best wood",
                            Name = "chair",
                            Price = 3200000m,
                            Profile = "/css/6d78ebf4-ee68-46e4-b68e-8be4c978044a.jpg"
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "green and red",
                            Name = "saled",
                            Price = 60000m,
                            Profile = "/css/9ffe609d-10c2-4232-9cca-8a0afbe42601.jpg"
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "asdajlasxa",
                            Name = "shar",
                            Price = 1456m,
                            Profile = "/css/55f21061-6ed3-4890-9eea-0b666a711af9.jpg"
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Monaseb Baray hameh senin",
                            Name = "SabziJat",
                            Price = 14000m,
                            Profile = "/css/49493ef7-b16c-427f-8ea8-aee2a67ff461.jpg"
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Baray jahizieh",
                            Name = "Home app",
                            Price = 280000000m,
                            Profile = "/css/9ffe609d-10c2-4232-9cca-8a0afbe42601.jpg"
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "besyarKhoob",
                            Name = "YakhChal",
                            Price = 30000000m,
                            Profile = "/css/d77a4624-8f71-47eb-b94b-bb517e2f3db7.jpg"
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "dar ranghay motafavet",
                            Name = "Goshi",
                            Price = 5000000m,
                            Profile = "/css/e0ce94cb-4ee1-46a4-8001-e1acc8aa315b.jpg"
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "hameh chiz ra khord ly konad",
                            Name = "hamzan",
                            Price = 4800000m,
                            Profile = "/css/7fd072b6-3bd1-453c-90e2-07e29fe3b12a.jpg"
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "besyar dag my koonad",
                            Name = "snaksaz",
                            Price = 2500000m,
                            Profile = "/css/8db76f47-db5c-4828-85ac-9ab24ab1ab3c.jpg"
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "khoshPokht",
                            Name = "Nan",
                            Price = 3700m,
                            Profile = "/css/6d78ebf4-ee68-46e4-b68e-8be4c978044a.jpg"
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "a book that  you can read",
                            Name = "book",
                            Price = 145900m,
                            Profile = "/css/8012f3fb-645c-4ca4-acdf-a612e3ff7d8b.jpg"
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "have blue and yellow",
                            Name = "bag",
                            Price = 25000000m,
                            Profile = "/css/40e2420a-7d60-437d-83b9-4fdf7a07455d.jpg"
                        });
                });

            modelBuilder.Entity("MahdiShop.DataLayer.Models.User.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordRip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UserPhone")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Password = "1234",
                            UserEmail = "Admin@gmail.com",
                            UserName = "Admin",
                            UserPhone = "090000000000"
                        });
                });

            modelBuilder.Entity("MahdiShop.DataLayer.Models.Product.Product", b =>
                {
                    b.HasOne("MahdiShop.DataLayer.Models.Product.Category", "category")
                        .WithMany("product")
                        .HasForeignKey("CategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
